default: &default
  # If app should only be using a specific collection,
  # append "/collection/(collection_name)" to path
  api_path: http://localhost:3000/collection/chesnutt
  # path to iiif server, NOT including the project directory
  iiif_path: https://cdrhmedia.unl.edu/iiif/2

test:
  <<: *default

development:
  <<: *default
  api_path: http://localhost:3000/collection/chesnutt
  iiif_path: https://cdrhmedia.unl.edu/iiif/2

production:
  <<: *default
  api_path: https://cdrhapi.unl.edu/v1
  iiif_path: https://cdrhmedia.unl.edu/iiif/2
